baseURL = "https://compassionate-euler-7bd6b0.netlify.app/"
disqusShortname = "https-compassionate-euler-7bd6b0-netlify-app"
languageCode = "en-us"
title = "Luis yChun | Personal Knowledge Base and Notes"

[permalinks]
  posts = "/:filename/"

[params]
  dateFormat = "Jan 2, 2006"